# Generated by Django 4.1.3 on 2022-12-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesero',
            name='edad',
            field=models.IntegerField(default=0,blank=True,null=True),
        ),
    ]
